NAME = WOLF3D
#ICON = icon.png
#DESCRIPTION = 
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

#-----------------------------
include $(shell cedev-config --makefile)
